import { Fingerprint, KeyRound, QrCode, Zap } from "lucide-vue-next";
import type { Capability, Demo, Lang, RoadmapColumn } from "./types";

export const CLAIM_CODE = "K7Q9-M4VX-2PDA";
export const QR_LOGIN_PAYLOAD = "https://qauth.dev/approve?session=demo-login-session-7f3c&symbols=fox-moon-rocket-cherry";
export const VERIFY_EMOJIS = ["🦊", "🌙", "🚀", "🍒"];

export const copy = {
  zh: {
    demo: "进入 Demo",
    badge: "Device-first Authentication Engine",
    heroA: "把登录体验改成",
    heroB: "可信设备确认",
    heroDesc: "QAuth 是一套无密码认证引擎：Passkey、扫码确认、设备绑定、二次验证都在一个漂亮清晰的体验里完成。",
    cta1: "立即进入 Demo",
    cta2: "查看安全设计",
    trusted: "可信设备",
    qr: "扫码批准",
    passkey: "Passkey 登录",
    live: "实时状态",
    nav: {
      position: "定位",
      capabilities: "能力",
      flow: "流程",
      demos: "Demo",
      security: "安全",
      roadmap: "路线图",
    },
    sections: {
      capabilities: "它能解决什么",
      capabilitiesDesc: "不是又一个普通登录页，而是把高风险认证流程产品化。",
      flow: "真实界面，而不是流程图",
      flowDesc: "用桌面登录窗口、手机确认页和服务端事件流模拟同一个会话，直接看产品该怎么发生。",
      demo: "产品化交互 Demo",
      demoDesc: "不再让用户逐个点流程按钮，而是打开一个真实界面模拟：二维码、手机批准、状态流、领取码与 WebAuthn 都在同一屏完成。",
      docs: "开发者文档",
      security: "安全设计",
      roadmap: "产品路线图",
    },
    docsDesc: "接入设计、接口边界、状态机和部署方式的入口。",
    close: "关闭",
    copied: "已复制",
    copyCode: "复制领取码",
    copyFailed: "复制失败，请手动复制",
    replay: "重放事件流",
    openDemo: "运行",
    runRealAction: "运行真实操作",
    actionReady: "已生成真实会话",
    passkeyUnavailable: "当前环境无法完成 Passkey，但已调用浏览器 WebAuthn API。",
    backDemo: "返回 Demo",
    reset: "重置",
    claimCode: "领取码",
    verifySymbols: "核对屏幕符号",
    demoLoginTitle: "正在登录 QAuth Workspace",
    demoApproveTitle: "确认这次登录",
    demoDesktopPanel: "桌面登录窗口",
    demoDesktopWaiting: "等待手机扫码",
    demoDesktopClaiming: "手机已确认",
    demoDesktopDone: "会话已建立",
    demoMobileScan: "扫描电脑上的二维码",
    demoMobileApprove: "核对后点击确认",
    demoMobileApproved: "已批准本次登录",
    demoApproved: "已批准",
    demoServerTruth: "服务端实际数据",
    demoNoClickHint: "演示会自动推进，不需要用户一步步点；当前界面状态：",
    demoRealtimeConnected: "已连接实时通道：{id}…",
    demoSessionIssued: "手机批准后，桌面端已领取一次性会话。",

    demoPage: {
      backHome: "返回首页",
      title: "实时认证演示",
      subtitle: "体验 QAuth 如何通过桌面扫码、手机确认、可信设备识别与会话验证完成一次安全登录。",
      modes: [
        { id: "standard", label: "标准流程" },
        { id: "mobile", label: "手机确认" },
        { id: "device", label: "可信设备" },
        { id: "proof", label: "计算挑战" },
      ],
      controls: { prev: "上一步", next: "下一步", play: "自动播放", pause: "暂停演示", reset: "重置" },
      desktop: { title: "桌面端发起登录", scan: "Scan with Trusted Device" },
      mobile: { title: "手机端确认请求" },
      device: { title: "识别可信设备" },
      proof: {
        challenge: "Challenge Card",
        progress: "Progress Card",
        result: "Result Card",
        active: "Active",
        found: "Proof Found",
      },
      details: {
        view: "查看技术细节",
        hide: "收起技术细节",
        sessionId: "qa_7K92M4",
        challengeId: "ch_62f9a8c1",
        deviceKey: "dk_7b49…91fa",
      },
      steps: {
        standard: [
          { id: "request", title: "发起登录请求", description: "用户在桌面端点击登录按钮，应用向 QAuth 请求一次新的认证流程。", status: "Login Requested" },
          { id: "challenge", title: "创建短时效挑战", description: "QAuth 生成一次性 challenge，并为当前会话设置有效时间。", status: "Challenge Created" },
          { id: "qr", title: "展示扫码确认", description: "桌面端显示二维码，用户使用已绑定设备扫描并查看登录详情。", status: "Waiting for Approval" },
          { id: "approve", title: "手机端批准", description: "用户在手机端确认本次登录请求，避免静默授权或误操作。", status: "Approved on Trusted Device" },
          { id: "device", title: "识别可信设备", description: "QAuth 校验设备绑定关系，并确认请求来自可信上下文。", status: "Device Recognized" },
          { id: "verified", title: "完成会话验证", description: "认证通过后，应用获得已验证 session，用户安全进入系统。", status: "Session Verified" },
        ],
        mobile: [
          { id: "scan", title: "扫码后展示请求", description: "手机端展示应用、浏览器、设备与位置，让用户确认这次登录是否可信。", status: "Request Reviewed" },
          { id: "approve", title: "明确批准或拒绝", description: "批准按钮作为主操作，拒绝保持弱样式，避免误触造成静默授权。", status: "Mobile Approval" },
          { id: "complete", title: "返回桌面会话", description: "手机端确认后，桌面端只领取本次短时效会话。", status: "Session Approved" },
        ],
        device: [
          { id: "match", title: "匹配绑定设备", description: "QAuth 校验设备密钥、最近验证时间和浏览器绑定关系。", status: "Trusted Device" },
          { id: "context", title: "确认请求上下文", description: "设备、浏览器和会话必须来自同一个可信上下文。", status: "Device Recognized" },
          { id: "verified", title: "设备验证完成", description: "可信设备通过后，本次认证可以继续进入会话验证。", status: "Verified Device" },
        ],
        proof: [
          { id: "received", title: "接收计算挑战", description: "浏览器收到短时效 challenge 和难度要求。", status: "Challenge Received" },
          { id: "search", title: "开始查找 nonce", description: "浏览器执行轻量工作量证明，用于降低自动化请求风险。", status: "Nonce Search Started" },
          { id: "generated", title: "生成有效证明", description: "找到满足前缀难度的 nonce，并截断展示长 hash。", status: "Proof Generated" },
          { id: "submitted", title: "提交证明", description: "QAuth 校验 challenge、nonce、hash 和过期时间。", status: "Proof Submitted" },
          { id: "continued", title: "继续认证", description: "证明通过后，流程继续进入可信设备确认。", status: "Authentication Continued" },
        ],
      },
    },
  },
  en: {
    demo: "Open Demo",
    badge: "Device-first Authentication Engine",
    heroA: "Make sign-in feel like",
    heroB: "trusted device approval",
    heroDesc: "QAuth is a passwordless auth engine that brings passkeys, QR approval, device binding, and step-up verification into one polished flow.",
    cta1: "Open Demo Now",
    cta2: "View Security Design",
    trusted: "Trusted device",
    qr: "QR approval",
    passkey: "Passkey Sign-In",
    live: "Live Status",
    nav: {
      position: "Position",
      capabilities: "Capabilities",
      flow: "Flow",
      demos: "Demo",
      security: "Security",
      roadmap: "Roadmap",
    },
    sections: {
      capabilities: "What it fixes",
      capabilitiesDesc: "Not another generic login page — a productized high-risk authentication experience.",
      flow: "Real screens, not a flowchart",
      flowDesc: "Desktop sign-in, mobile approval, and server events are simulated as one session so the product behavior is visible.",
      demo: "Productized interaction demos",
      demoDesc: "Users no longer click through fake step buttons; each demo opens a real screen simulation with QR, mobile approval, status stream, claim code, and WebAuthn behavior.",
      docs: "Developer docs",
      security: "Security design",
      roadmap: "Product roadmap",
    },
    docsDesc: "Entry point for integration design, API boundaries, state machines, and deployment.",
    close: "Close",
    copied: "Copied",
    copyCode: "Copy Claim Code",
    copyFailed: "Copy failed; copy manually",
    replay: "Replay stream",
    openDemo: "Run",
    runRealAction: "Run Real Action",
    actionReady: "Real Session Generated",
    passkeyUnavailable: "This environment cannot finish passkey auth, but the browser WebAuthn API was invoked.",
    backDemo: "Back to Demo",
    reset: "Reset",
    claimCode: "Claim Code",
    verifySymbols: "Verify Symbols",
    demoLoginTitle: "Signing in to QAuth Workspace",
    demoApproveTitle: "Approve This Sign-In",
    demoDesktopPanel: "Desktop Sign-In Window",
    demoDesktopWaiting: "Waiting for Phone Scan",
    demoDesktopClaiming: "Phone Approved",
    demoDesktopDone: "Session Established",
    demoMobileScan: "Scan the Desktop QR Code",
    demoMobileApprove: "Review and Approve",
    demoMobileApproved: "This Sign-In Is Approved",
    demoApproved: "Approved",
    demoServerTruth: "Server-Side Data",
    demoNoClickHint: "The demo auto-advances instead of forcing step-by-step clicks; current screen state:",
    demoRealtimeConnected: "Realtime channel connected: {id}…",
    demoSessionIssued: "After mobile approval, the desktop claimed a one-time session.",

    demoPage: {
      backHome: "Back to Home",
      title: "Live Authentication Demo",
      subtitle: "See how QAuth completes a secure sign-in with QR confirmation, mobile approval, trusted device recognition and session verification.",
      modes: [
        { id: "standard", label: "Standard Flow" },
        { id: "mobile", label: "Mobile Approval" },
        { id: "device", label: "Trusted Device" },
        { id: "proof", label: "Proof Challenge" },
      ],
      controls: { prev: "Previous", next: "Next", play: "Auto Play", pause: "Pause Demo", reset: "Reset" },
      desktop: { title: "Desktop Sign-In", scan: "Scan with Trusted Device" },
      mobile: { title: "Mobile Approval Request" },
      device: { title: "Trusted Device Recognition" },
      proof: {
        challenge: "Challenge Card",
        progress: "Progress Card",
        result: "Result Card",
        active: "Active",
        found: "Proof Found",
      },
      details: {
        view: "View Technical Details",
        hide: "Hide Technical Details",
        sessionId: "qa_7K92M4",
        challengeId: "ch_62f9a8c1",
        deviceKey: "dk_7b49…91fa",
      },
      steps: {
        standard: [
          { id: "request", title: "Request Sign-In", description: "The user clicks sign in on desktop, and the app requests a new authentication flow from QAuth.", status: "Login Requested" },
          { id: "challenge", title: "Create Short-Lived Challenge", description: "QAuth generates a one-time challenge and sets an expiry for the current session.", status: "Challenge Created" },
          { id: "qr", title: "Show QR Confirmation", description: "The desktop shows a QR code so the user can scan with a bound device and review the sign-in details.", status: "Waiting for Approval" },
          { id: "approve", title: "Approve on Mobile", description: "The user explicitly approves the request on mobile, avoiding silent authorization or accidental sign-ins.", status: "Approved on Trusted Device" },
          { id: "device", title: "Recognize Trusted Device", description: "QAuth verifies the device binding and confirms the request came from a trusted context.", status: "Device Recognized" },
          { id: "verified", title: "Verify Session", description: "After authentication succeeds, the app receives a verified session and safely continues to the workspace.", status: "Session Verified" },
        ],
        mobile: [
          { id: "scan", title: "Review the Request", description: "The mobile screen shows app, browser, device and location so the user can decide whether the request is trusted.", status: "Request Reviewed" },
          { id: "approve", title: "Approve or Deny", description: "Approve is the primary action while Deny remains secondary, reducing accidental authorization.", status: "Mobile Approval" },
          { id: "complete", title: "Return the Desktop Session", description: "After mobile approval, the desktop claims only this short-lived session.", status: "Session Approved" },
        ],
        device: [
          { id: "match", title: "Match the Bound Device", description: "QAuth checks the device key, recent verification time and browser binding.", status: "Trusted Device" },
          { id: "context", title: "Confirm Request Context", description: "Device, browser and session must all belong to the same trusted context.", status: "Device Recognized" },
          { id: "verified", title: "Complete Device Verification", description: "Once the trusted device passes verification, authentication can proceed to session verification.", status: "Verified Device" },
        ],
        proof: [
          { id: "received", title: "Receive Challenge", description: "The browser receives a short-lived challenge and a difficulty requirement.", status: "Challenge Received" },
          { id: "search", title: "Start Nonce Search", description: "The browser performs a lightweight proof-of-work to reduce automated request risk.", status: "Nonce Search Started" },
          { id: "generated", title: "Generate Proof", description: "A nonce satisfying the prefix difficulty is found, while the long hash is truncated in the UI.", status: "Proof Generated" },
          { id: "submitted", title: "Submit Proof", description: "QAuth verifies the challenge, nonce, hash and expiry window.", status: "Proof Submitted" },
          { id: "continued", title: "Continue Authentication", description: "After proof verification passes, the flow continues to trusted device confirmation.", status: "Authentication Continued" },
        ],
      },
    },
  },
} as const;

export const capabilities: Record<Lang, Capability[]> = {
  zh: [
    { icon: Fingerprint, title: "Passkey 优先", desc: "用设备解锁、面容或指纹完成登录，服务端只保存公钥。" },
    { icon: QrCode, title: "电脑扫码确认", desc: "二维码只包含会话编号，手机核对请求后把会话交回原浏览器。" },
    { icon: Zap, title: "抗滥用挑战", desc: "敏感入口前增加轻量计算挑战，提高机器人刷接口成本。" },
    { icon: KeyRound, title: "一次性领取码", desc: "老浏览器没有实时通道时，也能通过短时手动码完成登录。" },
  ],
  en: [
    { icon: Fingerprint, title: "Passkey-first", desc: "Sign in with device unlock, Face ID, or fingerprint. The server stores public keys only." },
    { icon: QrCode, title: "Desktop QR Approval", desc: "The QR contains only a session id; phone approval returns the session to the original browser." },
    { icon: Zap, title: "Abuse challenge", desc: "A lightweight puzzle before sensitive entry points raises bot and brute-force costs." },
    { icon: KeyRound, title: "One-time claim code", desc: "Legacy browsers can still sign in with a short-lived manual fallback code." },
  ],
};

export const flow: Record<Lang, string[]> = {
  zh: ["电脑创建扫码会话", "手机扫码并核对设备符号", "Passkey / 设备解锁批准", "服务端校验绑定关系", "原浏览器自动登录"],
  en: ["Desktop creates QR session", "Phone scans and checks symbols", "Passkey / device unlock approves", "Server validates device binding", "Original browser signs in"],
};

export const demoItems: Record<Lang, Demo[]> = {
  zh: [
    { id: "desktopQr", icon: "💻", title: "电脑二维码登录", desc: "桌面展示二维码、设备符号和实时等待状态。", accent: "from-sky-500 to-cyan-400", steps: ["生成 login_session_id", "展示二维码", "等待手机扫码", "领取已批准会话"] },
    { id: "mobileConfirm", icon: "📱", title: "手机确认登录", desc: "手机核对地点、设备和屏幕符号后批准。", accent: "from-violet-500 to-fuchsia-500", steps: ["扫描二维码", "核对请求来源", "设备解锁", "批准本次登录"] },
    { id: "pow", icon: "🧮", title: "计算挑战", desc: "浏览器完成轻量工作量证明后继续登录。", accent: "from-amber-500 to-orange-500", steps: ["拉取挑战", "本地寻找 nonce", "提交证明", "继续认证"] },
    { id: "register", icon: "🔐", title: "Passkey 注册", desc: "调用浏览器 WebAuthn 创建真实 Passkey 凭证。", accent: "from-emerald-500 to-teal-400", steps: ["创建注册挑战", "调用浏览器 Passkey", "保存公钥", "绑定可信设备"] },
    { id: "passkeyLogin", icon: "🛡️", title: "Passkey 登录", desc: "调用浏览器 WebAuthn 获取真实签名断言。", accent: "from-indigo-500 to-blue-500", steps: ["创建登录挑战", "设备完成签名", "服务端验证签名", "建立会话"] },
    { id: "classicDesktop", icon: "🗝️", title: "电脑领取码", desc: "没有实时通道时，电脑输入手机显示的一次性码。", accent: "from-rose-500 to-pink-500", steps: ["手机完成验证", "显示领取码", "电脑输入领取码", "领取码失效"] },
    { id: "classicMobile", icon: "📲", title: "手机领取码", desc: "手机端生成短时一次性登录码。", accent: "from-lime-500 to-emerald-400", steps: ["核对电脑符号", "设备验证", "生成 60 秒码", "提示电脑输入"] },
    { id: "sseFlow", icon: "📡", title: "SSE 状态流", desc: "演示连接、扫码、批准、领取会话的事件流。", accent: "from-slate-700 to-zinc-500", steps: ["连接已建立", "手机已扫码", "手机已确认", "电脑领取会话"] },
  ],
  en: [
    { id: "desktopQr", icon: "💻", title: "Desktop QR Sign-In", desc: "Desktop shows QR, symbols, and live waiting state.", accent: "from-sky-500 to-cyan-400", steps: ["Create login_session_id", "Show QR Code", "Wait for Phone Scan", "Claim Approved Session"] },
    { id: "mobileConfirm", icon: "📱", title: "Mobile Approval", desc: "Phone checks location, device, and screen symbols before approval.", accent: "from-violet-500 to-fuchsia-500", steps: ["Scan QR", "Review request source", "Unlock device", "Approve This Sign-In"] },
    { id: "pow", icon: "🧮", title: "Proof Challenge", desc: "Browser solves a light proof-of-work before continuing.", accent: "from-amber-500 to-orange-500", steps: ["Fetch Challenge", "Find Nonce Locally", "Submit Proof", "Continue Auth"] },
    { id: "register", icon: "🔐", title: "Passkey Registration", desc: "Call browser WebAuthn to create a real passkey credential.", accent: "from-emerald-500 to-teal-400", steps: ["Create challenge", "Call Browser Passkey", "Store Public Key", "Bind Trusted Device"] },
    { id: "passkeyLogin", icon: "🛡️", title: "Passkey Sign-In", desc: "Call browser WebAuthn to request a real signed assertion.", accent: "from-indigo-500 to-blue-500", steps: ["Create Login Challenge", "Device Signs", "Server Verifies", "Create Session"] },
    { id: "classicDesktop", icon: "🗝️", title: "Desktop Claim Code", desc: "Desktop enters a one-time code shown on phone when realtime is unavailable.", accent: "from-rose-500 to-pink-500", steps: ["Phone Verifies", "Show Claim Code", "Desktop Enters Code", "Code Expires"] },
    { id: "classicMobile", icon: "📲", title: "Mobile Claim Code", desc: "Phone generates a short-lived one-time sign-in code.", accent: "from-lime-500 to-emerald-400", steps: ["Check Desktop Symbols", "Verify Device", "Generate 60s code", "Prompt Desktop Entry"] },
    { id: "sseFlow", icon: "📡", title: "SSE Status Stream", desc: "Show connect, scan, approve, and claim-session events.", accent: "from-slate-700 to-zinc-500", steps: ["Connection Opened", "Phone Scanned", "Phone Approved", "Desktop Claimed Session"] },
  ],
};

export const docsItems: Record<Lang, string[]> = {
  zh: ["API 设计", "WebAuthn 验证流程", "扫码会话状态机", "数据库设计", "部署方式", "OAuth / OIDC 兼容设计"],
  en: ["API design", "WebAuthn verification", "QR session state machine", "Database schema", "Deployment", "OAuth / OIDC compatibility"],
};

export const protections: Record<Lang, string[]> = {
  zh: ["二维码不携带令牌或密钥", "电脑登录绑定原始浏览器", "领取码短时有效且一次性使用", "敏感操作需要重新验证", "计算挑战绑定具体操作", "服务端只保存必要的公钥与哈希"],
  en: ["QR carries no tokens or keys", "Desktop sign-in binds to the original browser", "Claim Codes are short-lived and one-time", "Sensitive actions require fresh verification", "Challenges bind to concrete operations", "Server stores only necessary public keys and hashes"],
};

export const roadmap: Record<Lang, RoadmapColumn[]> = {
  zh: [
    { title: "当前可体验", items: ["真实二维码与会话生成", "8 个真实浏览器 Demo", "主题与语言切换", "Web Crypto / WebAuthn 浏览器调用"] },
    { title: "正在实现", items: ["WebAuthn 服务端验证", "扫码状态机", "设备管理页面", "审计日志"] },
    { title: "未来计划", items: ["OAuth / OIDC 接入层", "风险策略控制台", "多产品租户", "生产部署模板"] },
  ],
  en: [
    { title: "Available now", items: ["Real QR and session generation", "8 real browser demos", "Theme and language toggle", "Web Crypto / WebAuthn browser calls"] },
    { title: "In progress", items: ["WebAuthn server verification", "QR session state machine", "Device management", "Audit logs"] },
    { title: "Planned", items: ["OAuth / OIDC layer", "Risk policy console", "Multi-product tenants", "Production deployment templates"] },
  ],
};
